name: Action For Translations
description: GitHub Action for pushing and pulling translations
author: emilnordh
inputs:
  token:
    required: true
    description: Lokalise API Token
  project:
    required: true
    description: Lokalise Project ID
  path:
    required: true
    description: |
      Direcotry path for translation files to upload. It supports path-to-regexp expressions and you must define the :locale param. Example: ./examples/:locale/messages.po.
  tags:
    required: false
    description: A list of tags. The list is a newline-delimited string.
  upload:
    required: false
    default: false
    description: Set this to true to upload translation files.
  download:
    required: false
    default: false
    description: Set this to true to download translation files.
outputs:
  uploads:
    description: A new-line separated list of all the uploaded translation files
  downloads:
    description: A new-line separated list of all the downloaded translation files
runs:
  using: node16
  main: dist/index.js
