name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Version and Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
        with:
          semantic_version: 19
      # If there is a new version published, let's say v1.1.0
      # then this step will update branch "v1" to this commit
      - name: Push major version updates
        if: steps.release.outputs.new_release_published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}
